---
title: "R Notebook"
output: html_notebook
---

# Background
This notebook accompanies the book *A-Practical-Primer-in-Human-Complex-Genetics*.

# Session information 

------

    Version:     v1.0.0
    Last update: 2022-03-04
    Written by:  Sander W. van der Laan (s.w.vanderlaan-2[at]umcutrecht.nl).
    Description: Data notebook accompanying 'A-Practical-Primer-in-Human-Complex-Genetics'. 
    Minimum requirements: R version 3.5.2 (2018-12-20) -- 'Eggshell Igloo', macOS Mojave (10.14.2).
    
    Changes log
    * v1.0.0 Initial version. 

  
------

```{r eval = TRUE}
sessionInfo()
```


## Saving environment

Saving data to RDS.
```{r saving-as-RDS, message=FALSE, warning=FALSE}

# Save as RDS
# saveRDS(AEMS450K1.SE, paste0(OUT_loc, "/",Today,".",PROJECTNAME,".AEMS450K1.SE.allClinData.rds"))


# AEMS450K1.SE <- readRDS(paste0(OUT_loc, "/",Today,".",PROJECTNAME,".AEMS450K1.SE.allClinData.rds"))


```


## Cleaning environment
```{r cleaning-environment, message=FALSE, warning=FALSE}

```

```{r Saving}
save.image(paste0(getwd(),
                  "/A-Practical-Primer-in-Human-Complex-Genetics.RData"))
```

------
<sup>&copy; 1979-2022 Sander W. van der Laan | s.w.vanderlaan-2[at]umcutrecht.nl | [swvanderlaan.github.io](https://swvanderlaan.github.io).</sup>
------
